/// Flutter icons CustomIcons3
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons3
///      fonts:
///       - asset: fonts/CustomIcons3.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons3 {
  CustomIcons3._();

  static const _kFontFam = 'CustomIcons3';
  static const String? _kFontPkg = null;

  static const IconData fblogo = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
